apiVersion: v1
kind: ConfigMap
metadata:
  name: internity-config
data:
  NODE_ENV: production
  APP_URL: http://internity.192.168.0.103.sslip.io
  STAFF_APP_URL: http://staff.192.168.0.103.sslip.io
  PUBLIC_CORS_ORIGIN: http://internity.192.168.0.103.sslip.io
  STAFF_CORS_ORIGIN: http://staff.192.168.0.103.sslip.io
  JWT_EXPIRES_IN: 8h
  COOKIE_SECURE: "false"
  TRUST_PROXY: "true"
  GROQ_MODEL: qwen/qwen3.8-27b
  UPLOAD_DIR: /data/uploads
  UPLOAD_MAX_MB: "10"
