apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internity
spec:
  ingressClassName: traefik
  rules:
    - host: internity.192.168.0.103.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http
    - host: api.192.168.0.103.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-public
                port:
                  name: http
    - host: staff.192.168.0.103.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: staff
                port:
                  name: http
    - host: staff-api.192.168.0.103.sslip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-staff
                port:
                  name: http
